# runtime: python39
# entrypoint: uvicorn main:app --host=0.0.0.0 --port=8080

# handlers:
# - url: /.*
#   script: auto

# env_variables:
#   PYTHONUNBUFFERED: "true"


runtime: python39  # replace with your Python version
instance_class: F2  # choose an instance class based on your needs
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
entrypoint: gunicorn -b :$PORT main:app  # replace 'main' with your Python script's filename without the .py extension
